name: "openai"
backend: "python"

input [
  {
    name: "DUMMY_INPUT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]